DROP TABLE PRAVEEN.CUSTOMER_COMMUNICATION;
DROP TABLE PRAVEEN.CUSTOMER_ADDRESS;
DROP TABLE PRAVEEN.CUSTOMER;
CREATE TABLE PRAVEEN.CUSTOMER (
  CUSTOMER_ID varchar(20) PRIMARY KEY,
  PASSWORD varchar(100) NOT NULL,
  FIRST_NAME varchar(50) NOT NULL,
  LAST_NAME varchar(50) NOT NULL,
  GENDER varchar(1) NOT NULL,
  ENABLED varchar(1) NOT NULL,
  ACCOUNT_NON_EXPIRED varchar(1) NOT NULL,
  CREDENTIALS_NON_EXPIRED varchar(1) NOT NULL,
  ACCOUNT_NON_LOCKED varchar(1) NOT NULL
) ;

CREATE TABLE PRAVEEN.CUSTOMER_ADDRESS (
  CUSTOMER_ID varchar(20) NOT NULL,
  STREET varchar(50) NOT NULL,
  HOUSENO varchar(10) NOT NULL,
  CITY varchar(100) NOT NULL,
  PINCODE varchar(10) NOT NULL,
  COUNTRY varchar(50) NOT NULL
);

CREATE TABLE PRAVEEN.CUSTOMER_COMMUNICATION (
  CUSTOMER_ID varchar(20) NOT NULL,
  EMAIL_ID varchar(100) NOT NULL,
  COUNTRY_CODE varchar(10) NOT NULL,
  PHONE_NO varchar(50) NOT NULL
);

INSERT INTO PRAVEEN.CUSTOMER VALUES('111','PASSWORD111','PRAVEEN KUMAR','RAJA','M','Y','Y','Y','Y');
INSERT INTO PRAVEEN.CUSTOMER VALUES('222','PASSWORD222','SHANKAR','KUMAR','M','Y','Y','Y','Y');
INSERT INTO PRAVEEN.CUSTOMER VALUES('333','PASSWORD333','PURNA','D','M','Y','Y','Y','Y');

INSERT INTO PRAVEEN.CUSTOMER_ADDRESS VALUES('111','KURELLA','13','VZM','535002','INDIA');
INSERT INTO PRAVEEN.CUSTOMER_ADDRESS VALUES('222','GUNTURU','15','PUN','535001','INDIA');
INSERT INTO PRAVEEN.CUSTOMER_ADDRESS VALUES('333','SUNDARA','17','NELLORE','535005','INDIA');

INSERT INTO PRAVEEN.CUSTOMER_COMMUNICATION VALUES('111','PKRAJA@ITSSGLOBAL.COM','91','9912547576');
INSERT INTO PRAVEEN.CUSTOMER_COMMUNICATION VALUES('222','SHANKAR@ITSSGLOBAL.COM','91','9912547576');
INSERT INTO PRAVEEN.CUSTOMER_COMMUNICATION VALUES('333','PURNA@ITSSGLOBAL.COM','91','9912547576');