LOAD DATA
INFILE 'C://Projects//HongKong_BCT//POC_SpringBoot//SQLLoaderFiles//IN//CustomerAddress.csv'
INSERT INTO TABLE CUSTOMER_ADDRESS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CUSTOMER_ID,
STREET,
HOUSENO,
CITY,
PINCODE,
COUNTRY
)