LOAD DATA
INFILE 'C://Projects//HongKong_BCT//POC_SpringBoot//SQLLoaderFiles//IN//CustomerCommunication.csv'
INSERT INTO TABLE CUSTOMER_COMMUNICATION
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CUSTOMER_ID,
EMAIL_ID,
COUNTRY_CODE,
PHONE_NO
)