LOAD DATA
INFILE 'C://Projects//HongKong_BCT//POC_SpringBoot//SQLLoaderFiles//IN//Customers.csv'
INSERT INTO TABLE CUSTOMER
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CUSTOMER_ID,
PASSWORD,
FIRST_NAME,
LAST_NAME,
GENDER,
ENABLED,
ACCOUNT_NON_EXPIRED,
CREDENTIALS_NON_EXPIRED,
ACCOUNT_NON_LOCKED
)